language: php
php:
  - '7.3'
  - '7.4'
addons:
  apt:
    update: true
before_install:
  - echo "$pusher_key"
  - composer validate
install:
  - composer install --no-interaction
script:
  - vendor/bin/phpunit --coverage-text --testdox --verbose
deploy:
  provider: heroku
  api_key: $heroku_api_key
  app: lumen-pusher
  on:
    branch: backend