language: php
addons:
  apt:
    update: true
before_install:
  - composer validate
install:
  - composer install --no-interaction
script:
  - vendor/bin/phpunit --coverage-text --testdox --verbose
jobs:
  include:
    - php: '7.3'
    - php: '7.4'
      deploy:
        provider: heroku
        api_key: $heroku_api_key
        app: lumen-pusher
        on:
          branch: backend
        run:
          - "cp .env.example .env"
          - "php artisan migrate:fresh --seed --force --verbose"