dist: bionic
language: node_js
addons:
  apt:
    update: true
cache:
  directories:
  - node_modules
jobs:
  include:
    - node_js: '12'
    - node_js: '13'
    - node_js: '14'
    - node_js: 'lts'
    - node_js: 'stable'
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
        on:
          branch: frontend